[tool.ruff]
target-version = "py311"
line-length = 120
format = {quote-style = 'single'}

[tool.ruff.lint]
flake8-quotes = {inline-quotes = 'single', multiline-quotes = 'double'}
mccabe = { max-complexity = 20 }
pylint = { max-branches = 15 }
extend-select = [
    'C90',
    'I',
    'UP',
    'FBT',
    'B',
    'A',
    'COM',
    'C4',
    'ISC',
    'PIE',
    'PYI',
    'Q',
    'RET',
    'SLF',
    'SIM',
    'TID',
    'PL',
    'FLY',
    'PERF',
    'RUF',
]
ignore = [
    'PLR2004', # "magic values" are fine in single-file scripts
    'COM812', # formatter
    'ISC001', # formatter
]
